### PR TITLE
Update Dropdown.php

### PR DESCRIPTION
**Pull request by bestmomo**

### CODE REVIEW

**Comment by Enrica-r** [comment]
@bestmomo: Thank you very much for your quick solution.

The code line `:style="{'top': ($refs.dropdownButton.getBoundingClientRect().bottom + window.scrollY) + 'px', 'left':` has one disadvantage. If the trigger button is near the screen bottom, the box falls out of view.

I tried to replace it with `x-anchor.{{ $right ? 'bottom-end' : 'bottom-start' }}="$refs.dropdownButton"` but together with your class definition. Then it works as it should. Left and right positioning is working also.

**Comment by bestmomo** [comment]
Yes there is this issue and another one, when screen is hight it no longer sticks to the trigger. This issue is hard to manage...

**Comment by robsontenorio** [comment]
I think this issue can be solved by change some css class on original code from this component. 

I will give a try on next days.

**Comment by robsontenorio** [comment]
Closing this, please follow #483

**Pull request closed without merging**
