### PR TITLE
Table: fix horizontal overflow 

### PR DESCRIPTION
**Pull request by c-perez**

### CODE REVIEW

**Comment by robsontenorio** [comment]
Could you provide more details about the issue?

**Comment by c-perez** [comment]
I added details in Discord.

**Comment by c-perez** [comment]
Before
- Pagination buttons x scroll with the content of the table
Screencast from 26-07-2024 12_33_47

After
- No x scroll of the pagination elements
Screencast from 26-07-2024 12_34_23

**Comment by robsontenorio** [comment]
Thanks!

**Pull request merged**
