### PR TITLE
Add dynamic ID binding for Choice component

### PR DESCRIPTION
**Pull request by iurigustavo**
Replaced static UUID bindings with dynamic ID bindings using Alpine.js in the ChoicesOffline component. This change improves reactivity and ensures accurate element targeting within the component.

refs:
https://github.com/alpinejs/alpine/discussions/2989

### CODE REVIEW

**Comment by robsontenorio** [comment]
What bug does it solve ?

**Comment by iurigustavo** [comment]
Resolve the bug when filling in the options dynamically after component being created

**Comment by lucas-davi** [comment]
> What bug does it solve ?

#582

**Comment by robsontenorio** [comment]
Thanks!

**Pull request merged**
