### PR TITLE
Table: fix selectable (checkbox)

### LINKED ISSUE #430: Table: selectable with with-pagination not working on next page.
### maryUI version

1.30

### daisyUI version

4.7.3

### Livewire version

3.4

### What browsers are affected?

Chrome, Microsoft Edge

### What happened?

**Works only if refresh the page!**

https://github.com/robsontenorio/mary/assets/22216968/84be4393-7167-4448-a7de-0aef6a58a11b

### PR DESCRIPTION
**Pull request by robsontenorio**
Closes #430 #424

### CODE REVIEW

**Comment by Rattone** [comment]
@robsontenorio sorry if I bother you here, I would like to know if it is possible to have the source of ping.mary-ui.com. it would be very helpful and appreciated. anyway thank's for your job

**Comment by robsontenorio** [comment]
@Rattone 

You can get the demo by clicking on SOURCE CODE button. If you appreciate and want support my work. 

All demos are paid except for paper.mary-ui.com

**Comment by Rattone** [comment]
> @Rattone
> 
> You can get the demo by clicking on SOURCE CODE button. If you appreciate and want to support my work.
> 
> All demos are paid except for paper.mary-ui.com

Sorry but where can I buy it from? I couldn't find any buttons...

**Comment by Rattone** [comment]
> @Rattone
> 
> You can get the demo by clicking on SOURCE CODE button. If you appreciate and want to support my work.
> 
> All demos are paid except for paper.mary-ui.com

Yes I would like to, but I'm interested in the "backend" part of ping.mary-ui.com. Is it with websocket (reverb)? If I buy it will I find this part?

**Comment by robsontenorio** [comment]
You get what you see. Including Reverb/websocket.

**Pull request merged**
