### PR TITLE
Choices/ChoicesOffline: add keyboard support

### PR DESCRIPTION
**Pull request by akhmads**
- Press enter key to trigger dropdown
- Support tab, top/bottom arrow key button to select choice item
- Press enter key to select choice item
- Prevent arrow key (top, left, right, down) and tab from triggering search process

https://github.com/user-attachments/assets/b85a36ed-359f-434d-ba34-cd8f5f6269a1

### CODE REVIEW

**Comment by quileab** [comment]
Good work, waiting for PR merge

**Comment by robsontenorio** [comment]
@akhmads 

- It would more intuitive to make it work with "arrow down", as a first trigger. 
- The "enter" tigger is problem, because it will submit the form depending on where it is placed. So, "arrow down" it would be fine.

Could you please handle it?

When I click on this input it shows me the list by default (it is ok), but "arrow down" does not work. Just "tab", then "arrow down" works.

image

**Comment by akhmads** [comment]
Ok sir, I will try to fix it.

**Comment by akhmads** [comment]
I have made "down arrow" a dropdown trigger, please review
Thank you

**Comment by robsontenorio** [comment]
@akhmads I came up with another approach. Please, give a try.

**Pull request merged**
