### PR TITLE
Dropdown classes on slot

### PR DESCRIPTION
**Pull request by jedjones-uk**
Hello,

I've got another tweak I hope you will consider. When using the dropdowns with the trigger slot, it would be nice to be able to customise the classes which are applied to the summary.

### CODE REVIEW

**Comment by robsontenorio** [comment]
Hey @jedjones-uk ‘

Could you provide some sample code and  screenshots about its usage?

**Comment by jedjones-uk** [comment]
Sorry for the slow response @robsontenorio. I think I figured out a way around the specific issue. I will include my use case so you can consider if it's useful in general.

I have attached a screen shot of my page, and will include my AppLayout, and relevant sub-components.

The issue I had is my avatar dropdown needed to be more complex and required some extra positioning elements to work in place, I've since resolved that issue. The problem now is the grey background on the active item (below the search item) sticks to the side, it does this because there is an empty `div` after the x-mary-avatar div with with the class 'avatar' (line 33).

I could fix this in the avatar file obviously, but I think with more complex components coming for the sidebar, it would really help if they could make themselves responsive to changes in the collapse state.

image

image


```
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <link rel="apple-touch-icon" sizes="180x180" href="{{url('images/favicon/apple-touch-icon.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{url('images/favicon/favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{url('images/favicon/favicon-16x16.png')}}">
    <link rel="manifest" href="{{url('images/favicon/site.webmanifest')}}">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet"/>

    <!-- Scripts -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    @vite(\Nwidart\Modules\Module::getAssets())

    <!-- Styles -->
    @livewireStyles
</head>
<body class="min-h-screen font-sans antialiased bg-base-200/50 dark:bg-base-200">

<div class="bg-base-100 border-gray-100 border-b sticky top-0 z-10 lg:hidden">
    <div class="flex items-center px-6 py-5 max-w-screen-2xl mx-auto">
        <div class="flex-1 flex items-center">
            <a href="/">

                <div class="hidden-when-collapsed">
                    <div class="flex gap-2">
                        <img src="{{url($brand_logo)}}" alt="{{$brand_tagline}}" width="30" class="mt-1"/>
                        <span class="font-bold text-3xl mr-3">
                            {{$brand_app_name}}
                        </span>
                    </div>
                </div>

                <div class="display-when-collapsed hidden mx-5 mt-4 lg:mb-6 h-[28px]">
                    <img src="{{url($brand_logo)}}" alt="{{$brand_tagline}}" width="30" class="h-8">
                </div>
            </a>
        </div>

        <div class="flex items-center gap-4">
            <label for="main-drawer" class="lg:hidden mr-3">
                <x-mary-icon name="o-bars-3" class="cursor-pointer"/>
            </label>
        </div>
    </div>
</div>

<x-mary-main full-width>

    <x-slot:content>
        {{ $slot }}
    </x-slot:content>

    <x-slot:sidebar drawer="main-drawer" collapsible class="bg-white dark:bg-slate-600 !overflow-visible">

        <a href="/">
            <div class="hidden-when-collapsed p-5 pt-3">
                <div class="flex gap-2">
                    <img src="{{url($brand_logo)}}" alt="{{$brand_tagline}}" width="67" class="mt-1"/>
                    <span class="font-bold text-3xl mr-3">
                        {{$brand_app_name}}
                    </span>
                </div>
            </div>

            <!-- Display when collapsed -->
            <div class="display-when-collapsed hidden ms-1 mt-2 lg:mb-6 h-[60px]">
                <img src="{{url($brand_logo)}}" alt="{{$brand_tagline}}" width="60"/>
            </div>
        </a>

        <x-mary-menu activate-by-route>

            @foreach(\Modules\CommonUI\App\Menus\SidebarMenu::make()->tree() as $menuItem)
                <x-cui::recursive-menu-item :menuItem="$menuItem"/>
            @endforeach

            <x-mary-menu-item title="Home" icon="o-home" link="{{route('dashboard')}}"/>
            <x-mary-menu-item title="People" icon="o-user-group" link="{{route('people.index')}}"/>

        </x-mary-menu>
    </x-slot:sidebar>

</x-mary-main>

<x-mary-toast/>
<x-mary-theme-toggle class="hidden"/>

<script>
    document.documentElement.setAttribute("data-theme", localStorage.getItem("mary-theme")?.replaceAll("\"", ""))
    document.documentElement.setAttribute("class", localStorage.getItem("mary-theme")?.replaceAll("\"", ""))
</script>
</body>
@livewireScripts
@vite(['resources/js/app.js'])
</html>
```

x-cui::recursive-menu-item

```
@php
    $icon = $menuItem['attributes']['icon'] ?? null;
@endphp

@switch($menuItem['attributes']['type'])
    @case(\Modules\CommonUI\App\Enums\NavType::SUB_MENU)
        <x-mary-menu-sub :title="$menuItem['title']" :icon="$icon">
            @foreach($menuItem['children'] ?? [] as $subItem)
                <x-cui::recursive-menu-item :menuItem="$subItem"/>
            @endforeach
        </x-mary-menu-sub>

        @break

    @case(\Modules\CommonUI\App\Enums\NavType::DIVIDER)
        <x-mary-menu-separator :title="$menuItem['title']" :icon="$icon"/>
        @break

    @case(\Modules\CommonUI\App\Enums\NavType::COMPONENT)
        <x-dynamic-component :component="$menuItem['attributes']['component']"/>
        @break

    @case(\Modules\CommonUI\App\Enums\NavType::LIVEWIRE)
        @livewire($menuItem['attributes']['livewire'])
        @break

    @case(\Modules\CommonUI\App\Enums\NavType::POST_FORM)
        <form method="POST" action="{{ $menuItem['url']}}" x-data>
            @csrf
            <x-mary-menu-item @click.prevent="$root.submit();" :title="$menuItem['title']" :icon="$icon"/>
        </form>
        @break

    @case(\Modules\CommonUI\App\Enums\NavType::MENU_ITEM)
    @default
        <x-mary-menu-item
            :active="$menuItem['active']"
            :title="$menuItem['title']"
            :link="$menuItem['url']"
            :icon="$icon"
            :badge="$menuItem['attributes']['badge']??null"
            :badge-classes="$menuItem['attributes']['badgeClasses']??null"
            :external="$menuItem['attributes']['external']??false"
        />
@endswitch
```
Building the Menu
```
   $this->app->resolving(SidebarMenu::class, function (SidebarMenu $navigation): SidebarMenu {
            $navigation->add('', '', NavConfig::separator());
            $navigation->add('Header', '', NavConfig::component('cui::sidebar-header'));
            $navigation->add('', '', NavConfig::separator());
            $navigation->add('Global Search', '', NavConfig::livewire('global-search'));
            $navigation->add('', '', NavConfig::separator());

            return $navigation;
        });
```

cui::sidebar-header
```
<div class="my-3">
    <div x-data="{}" class="flex justify-between items-center gap-4 px-3 -mx-2 !-my-2 rounded">

        @dynamicComponentSlot('open-header-slot')

        <x-mary-dropdown>
            <x-slot:trigger>
                <x-mary-button icon="o-bell" class="btn-ghost"/>
            </x-slot:trigger>

            <x-mary-menu-item title="Placeholder"/>
        </x-mary-dropdown>

        <x-mary-dropdown>
            <x-slot:trigger>
                <x-mary-button icon="o-squares-2x2" class="btn-ghost"/>
            </x-slot:trigger>

            <x-mary-menu-item title="Archive"/>
            <x-mary-menu-item title="Move"/>
        </x-mary-dropdown>

    </div>
</div>
```

This is my avatar dropdown component which is loaded in place of `@dynamicComponentSlot('open-header-slot')`
```
<x-mary-dropdown>
    <x-slot:trigger>
        <div class="cursor-pointer btn btn-ghost p-0">
            <div class="flex justify-start items-center">
                <x-mary-avatar
                    image="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/michael-gough.png"
                    class="!w-12 !rounded-lg h-[47px]"/>
                <x-mary-icon name="o-chevron-down" class="ps-2 hidden-when-collapsed"/>
            </div>
        </div>
    </x-slot:trigger>

    <x-mary-avatar title="{{$user->name}}" subtitle="{{$user->email}}"
                   image="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/michael-gough.png"
                   class="!w-12 !rounded-lg h-[47px]"/>

    <x-mary-menu-separator/>
    <x-mary-menu-item title="Toggle Theme" icon="o-swatch" @click="$dispatch('mary-toggle-theme')"/>
    <x-mary-menu-separator/>

    @foreach($menu->tree() as $menuItem)
        <x-cui::recursive-menu-item :menuItem="$menuItem"/>
    @endforeach

</x-mary-dropdown>

```

**Comment by robsontenorio** [comment]
@jedjones-uk 

There is an easy way to solve this "user info + avatar" : 

Just use `x-list-tem`. It has internal special classes that sidebar uses to decide how to proper collapse it.
So you can place anything on `actions slot`, when sidebar is collapsed only avatar is shown. 


**https://mary-ui.com/docs/layout**

image


**This same approach is used on FLOW demo.**

image


image

**Comment by robsontenorio** [comment]
If your MR does not break current usage (collapse with x-list-item) we are good to go.

**Comment by jedjones-uk** [comment]
@robsontenorio Thank you as always

**Pull request merged**
