### PR TITLE
Bug fix: Double scroll on sidebar

### PR DESCRIPTION
**Pull request by satulg01**
This PR fix the isse opened here: https://github.com/robsontenorio/mary/issues/369

I've removed desnecessary height css propertie for remove the extra scroll

### CODE REVIEW

**Comment by robsontenorio** [comment]
Thanks for this!

Actually this “calc height” is used by “collapse button” on “sidebar template layout”. 

Could you please spin up a new project using and double check it ?

**Comment by satulg01** [comment]
Hi @robsontenorio, sorry but i'm initializing on the contribution's world and i dont know how to build the app and check it. Can you send me a article or tutorial for me learn how to do?

**Comment by satulg01** [comment]
Hi again @robsontenorio, i do this and make another changes.

image

This "calc height" was used with:

lg:top-[73px]
pb-[73px]

Only when attr "withNav" was passed for "x-main". All the cases was tested and functioning. Thank you

**Comment by robsontenorio** [comment]
Add this “collapsible” attribute on your current  template like this. It will show a “collapse button” at the end of menu. 

https://github.com/robsontenorio/mary/blob/601842de253f447fc58799bb5e5b1f0a69c13cc1/stubs/app.blade.php#L28

**Comment by robsontenorio** [comment]
Thank you! Solved by #364

**Pull request closed without merging**
