### PR TITLE
Add 'disabled' option to Radio component options

### PR DESCRIPTION
**Pull request by bimsonz**
Allow an option set to 'disable' an option by defining `disabled === true`

### CODE REVIEW

**Comment by bimsonz** [comment]
Considered adding the ability to define the `disabled` key but it felt a little unnecessary... what do you think ?

**Comment by robsontenorio** [comment]
Have you tested with this syntax `:disabled=“$myVar”` ?

**Comment by bimsonz** [comment]
To be honest, im not that familiar with that syntax, is it used with Alpine ? I've not tested anything outside of the blade implementation. Happy to if you can point me in that direction

**Comment by robsontenorio** [comment]
Any blade component variable can be bound to external variables . Try it `$myVar` as true/false and see.

**Comment by bimsonz** [comment]
Is this suggestion to cater for disabling the whole radio component? 
My intension is to add the ability for specific options to be disabled.

Sorry, excuse my confusion here!

**Comment by robsontenorio** [comment]
Thanks!

**Pull request merged**
