### PR TITLE
Tweak Sidebar height

### PR DESCRIPTION
**Pull request by jedjones-uk**
Tweak the height on the sidebar so that it fills to the page rather than screen size.

I've done this because in my case I would end up needing to scroll to see the collapsible button pinned to the bottom of the sidebar when I also had a nav header

### CODE REVIEW

**Comment by robsontenorio** [comment]
@jedjones-uk  I was aware about this issue ... Thanks!

I have a try your PR, but it seems we missed something else. Take look.


https://github.com/robsontenorio/mary/assets/118955/7530c107-667e-4803-bb6e-7f510bd13593

**Comment by robsontenorio** [comment]
I think the sidebar should be refactored to use some "flex css" design to push "collapse button" to the bottom.

Currently the "collapse button" is floating.

Can you handle this?

**Comment by jedjones-uk** [comment]
I am happy to take a look at it

**Comment by jedjones-uk** [comment]
So there is a few points to consider here, my use case of a Nav bar above the sidebar (outside of x-slot:content) is not really how daisyUI intends for it to be used, it's because of these I have had to add two in place style overrides for diasyUI. These are at line 46;

With the way it is now, it doesn't matter if you use the navbar as intended or the way I have it will always fit the screen size appropriately, with the collapse button positioned at the bottom

I have set it so if the line items in the menu were to be very long, it will use a max size of dvh and then scroll. This should match the behaviour of daisyUI.

You need to place `flex` on the body (or container of all these components), and `flex-col` if you have a navbar above the sidebar for it to work.

**Comment by jedjones-uk** [comment]
I have removed with-nav as it is not needed in this case. Unfortunately, because of the way it's structured, we cannot pull those final two classes into the component without a bigger, more fundamental change. I will provide examples of the 3 usages below to illustrate it.

Navbar above and external to content
This is the only case where you have to add flex and flex-col to the body:
```
 <body class="min-h-screen flex flex-col font-sans antialiased">

      <x-mary-nav sticky full-width>
          <x-slot:brand>
              <a href="/" class="flex items-center">
                  <span class="text-xl font-semibold text-gray-800 dark:text-white ml-2">
                  App
                  </span>
              </a>
          </x-slot:brand>

          <x-slot:actions>
              <x-mary-theme-toggle value="light"/>
          </x-slot:actions>
      </x-mary-nav>


      <x-mary-main full-width>
          <x-slot:sidebar drawer="main-drawer" collapsible class="bg-slate-200">
              <x-mary-menu activate-by-route>
                  <x-mary-menu-item title="Home" icon="o-home" link="{{route('dashboard')}}"/>
                  ...
              </x-mary-menu>
          </x-slot:sidebar>

          <x-slot:content>
              {{ $slot }}
          </x-slot:content>
          
      </x-mary-main>
    </body>
```


Nav in content (DaisyUI Design)
```
<body class="min-h-screen font-sans antialiased">
      <x-mary-main full-width>
          <x-slot:sidebar drawer="main-drawer" collapsible class="bg-slate-200">
              <x-mary-menu activate-by-route>
                  <x-mary-menu-item title="Home" icon="o-home" link="{{route('dashboard')}}"/>
                  ...
              </x-mary-menu>
          </x-slot:sidebar>

          <x-slot:content>
              <x-mary-nav sticky full-width>
                  <x-slot:brand>
                      <a href="/" class="flex items-center">
                          <span class="text-xl font-semibold text-gray-800 dark:text-white ml-2">
                          App
                          </span>
                      </a>
                  </x-slot:brand>

                  <x-slot:actions>
                      <x-mary-theme-toggle value="light"/>
                  </x-slot:actions>
              </x-mary-nav>
          
              {{ $slot }}
          </x-slot:content>
          
      </x-mary-main>
    </body>
```


Sidebar Only
```
 <body class="min-h-screen font-sans antialiased">
      <x-mary-main full-width>
          <x-slot:sidebar drawer="main-drawer" collapsible class="bg-slate-200">
              <x-mary-menu activate-by-route>
                  <x-mary-menu-item title="Home" icon="o-home" link="{{route('dashboard')}}"/>
                  ...
              </x-mary-menu>
          </x-slot:sidebar>

          <x-slot:content>          
              {{ $slot }}
          </x-slot:content>
          
      </x-mary-main>
    </body>
```

**Comment by robsontenorio** [comment]
I have pull again your branch and have tried the examples you have provided.

But all fails when we have large vertical content.

Gosh! This is a hard one. Let me start another PR from the ground and will see if we can fix the "collapse button" overflow case.

**Comment by robsontenorio** [comment]
Solved by #337

**Pull request closed without merging**
