### PR TITLE
Accordion/Collapse: New components 

### PR DESCRIPTION
**Pull request by dormammuuuuu**
image

image

image

image

# Note (from Daisy):
- Accordion uses the same style as the collapse component, but it works with radio inputs. You can control which item to be open by checking/unchecking the hidden radio input.
- All radio inputs with the same name work together and only one of them can be open at a time. If you have more than one set of accordion items on a page, use different names for the radio inputs on each set.

## Usage of Collapse:
```
<x-collapse>
    <x-slot:heading>
        Hello World
    </x-slot:heading>
    <x-slot:content>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit
    </x-slot:content>
</x-collapse>
```
Options:
- **accordion-item**: (attr) Defines if the element is part of an accordion group.
- **name**: (attr="value") The name of the radio group if part of an accordion.
- **checked**: (attr) Whether the component is checked by default or not.
- **collapse-arrow**: (attr) Accordion with arrow icon.
- **collapse-plus-minus**: (attr) Accordion with plus/minus icon.

## Usage of Accordion:
```
<x-accordion join>
  <x-collapse name="test-1" collapse-plus-minus checked> // Notice the collapse-plus-minus & checked attribute
    <x-slot:heading>Test 1</x-slot:heading>
    <x-slot:content>
        <p>World Hello</p>
    </x-slot:content>
  </x-collapse>
  <x-collapse name="test-1" collapse-arrow> // Notice the collapse-arrow attribute
    <x-slot:heading class="!bg-blue-500">Test 2</x-slot:heading>
    <x-slot:content class="!bg-blue-500">
        <p>Hello World</p>
    </x-slot:content>
  </x-collapse>
</x-accordion>
```
Options:
- **join**: (attr) To join the items together and handle border radius automatically.

### CODE REVIEW

**Comment by robsontenorio** [comment]
Thanks for this ! Will review soon.

**Comment by hamannjames** [comment]
Was just thinking the library needs something like this. Very cool! Excited for the review and (maybe) pull!

**Comment by robsontenorio** [comment]
I will review soon. Just let me finish another tweaks.

**Comment by hamannjames** [comment]
@robsontenorio trying it in an app I am working on now.

**Pull request merged**
