### PR TITLE
Tabs: to allow full external customisation

### PR DESCRIPTION
**Pull request by SOG-web**
I added the ability for devs to customize the tabs component to there use case. I will add update to the docs next

### CODE REVIEW

**Comment by SOG-web** [comment]
I can't find the docs site in the repo

**Comment by robsontenorio** [comment]
https://github.com/robsontenorio/mary-ui.com

**Comment by SOG-web** [comment]
This is a simple different use case

```blade
<x-custom-tabs label-class="font-semibold" label-div-class="flex overflow-x-auto w-full" active-class='bg-primary'
                   wire:model="selectedTab"
                   class="!border-none w-full">
        <x-tab id="all-tab" name="all-tab" label="All" class="!border-none">
            <div class="w-full flex flex-col items-start justify-start gap-4 !border-none">
                <div>All</div>
            </div>
        </x-tab>
        <x-tab name="graded-tab" label="Graded">
            <div>Tricks</div>
        </x-tab>
        <x-tab name="ungraded-tab">
            <x-slot:label>
                Ungraded
                <x-badge value="3" class="badge-primary"/>
            </x-slot:label>
            <div>Musics</div>
        </x-tab>
    </x-custom-tabs>
```

**Comment by SOG-web** [comment]
> https://github.com/robsontenorio/mary-ui.com

Thanks, can go ahead to update the docs

**Comment by SOG-web** [comment]
docs updated, pull request sent. Thanks so much

**Comment by robsontenorio** [comment]
Thanks!

**Pull request merged**
