### PR TITLE
Icon: add icon set config option

### PR DESCRIPTION
**Pull request by REJack**
Add support to adjust/replace the hardcoded `heroicon` inside the Icon component to allow dot-less naming for non heroicons

### CODE REVIEW

**Comment by robsontenorio** [comment]
In order to make you we won’t introduce BC in the future, could you please refactor it to follow the current  hierarchy ?

“components - icon - set”

Just like we did on Spotlight config.

**Comment by REJack** [comment]
I've adjusted the config hierachy 😄

**Comment by robsontenorio** [comment]
Thank you!

**Comment by REJack** [comment]
Ok, may we can use that for v2 release or so 😄

**Comment by REJack** [comment]
I have thought about the revert, would it be option too if I would extend all the components with config-able icons? that would be a break point for me too, i don't like the heroicons 😅 I would create a WIP/Draft PR so you can track my changes from that and we can discuss over them directly.

**Comment by winavin** [comment]
First of all, thank you for such a good package.

For icons required by internal components we can create separate "svg" folder in "resources". in balde-ui-icons we can create custom icon sets based on folder. so all mary-ui components will use mary-icons set. and user can use default icon set whatever he want.

for example

```
class ToastException extends Exception
{
    protected string $icon = 'o-information-circle';  // - remove
    protected string $icon = config('icons.defaults.toast-exception.icon');  // + add
```
``` 
config.php

"icons" =>[
"default-set" => "heroicons",
"defaults"=>[
    "toast-exception" => "mary.information-circle",
   // other components
],
]
```

this will solve all problems.
I know this will take some time, but hope to see something like this in next version.

**Pull request merged**
